# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: easy-article-pic
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: Astorm
    website: https://github.com/astorm-z
  logo: logo.png
  homepage: https://github.com/astorm-z/halo-plugin-easy-article-pic#readme
  repo: https://github.com/astorm-z/halo-plugin-easy-article-pic
  issues: https://github.com/astorm-z/halo-plugin-easy-article-pic/issues
  displayName: "简易文章配图"
  description: "结合 Cover View, 快速给文章加上专属配图"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
